name: Fix lib folder
on: workflow_dispatch
jobs:
  fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Rename lib to _lib
        run: |
          mv educore/client/api/lib educore/client/api/_lib
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Rename lib to _lib"
          git push
